export const CALL_GET_MOVIES = 'CALL_GET_MOVIES';
export const CALL_GET_MOVIES_SUCCESS = 'CALL_GET_MOVIES_SUCCESS';
export const CALL_GET_MOVIES_FAILURE = 'CALL_GET_MOVIES_FAILURE';

export const UPDATE_LIKED_MOVIES = 'UPDATE_LIKED_MOVIES';